version: 0.0
os: linux
files:
  - source: build
    destination: /var/www/html/build
  - source: dashtar-backend
    destination: /var/www/html/dashtar-backend
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/new_script
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root